name: nix-checker

on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  run-nix-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.1
      - name: Run nix flake check
        run: nix flake check --all-systems --print-build-logs

  run-nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.1
      - name: Run nix-build with flakes
        run: nix build .#default
